name: test

on:
  push:
    branches: [ public ]
  pull_request:
    branches: [ public ]
  workflow_dispatch: # or manual

jobs:

  test:
    strategy:
      matrix:
        os   : [ ubuntu-latest, windows-latest, macos-latest ]
        node : [ 12, 14, 16, 18 ]
    runs-on: ${{ matrix.os }}
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: install node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: install node_modules
      run: npm ci

    - name: run tests
      run: npm run test
